const Codes = {
  SUCCESS: 200,
  INTERNAL_ERROR: 500,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  ACCESS_DENIED: 404,
  INVALID_TOKEN: -1,
  INVALID_APIKEY: -1,
  RESPONSE_ERROR: 0,
  RESPONSE_SUCCESS: 1,
  MISSING_FIELD: 2,
  NO_DATA_FOUND: 3,
};

export default Codes;
